import Head from 'next/head'
import {Roboto_Slab} from '@next/font/google'
import styles from '@/styles/Home.module.scss'

const robotoSlab = Roboto_Slab({subsets: ['latin']})

export default function Home() {

  return (
    <div className={robotoSlab.className}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <nav>
        <ul className={styles.nav}>
          <li><a href="#projects">projects</a></li>
          <li><a href="#youtube">youtube</a></li>
          <li><a href="#github">github</a></li>
          <li><a href="#articles">articles</a></li>
          <li><a href="#contact">contact</a></li>
        </ul>
      </nav>
      <main className={styles.main}>
        <div className={styles.logo}>
          <h1>dom the dev</h1> <span>Fullstack JavaScript Developer never tired of learning and always up for new projects.</span>
        </div>
        <div className={`${styles.page} ${styles.start}`}/>

        <div id={'projects'} className={`${styles.page} ${styles.projects}`}>
          <ul>
            <li>project 1</li>
            <li>project 2</li>
            <li>project 3</li>
          </ul>
        </div>

        <div id={'youtube'} className={`${styles.page} ${styles.projects}`}>
          <ul>
            <li>youtube 1</li>
            <li>youtube 2</li>
            <li>youtube 3</li>
            <li>youtube 4</li>
            <li>youtube 5</li>
          </ul>
        </div>

        <div id={'github'} className={`${styles.page} ${styles.projects}`}>
          <ul>
            <li>github 1</li>
            <li>github 2</li>
            <li>github 3</li>
          </ul>
        </div>

        <div id={'articles'} className={`${styles.page} ${styles.projects}`}>
          <ul>
            <li>articles 1</li>
            <li>articles 2</li>
            <li>articles 3</li>
          </ul>
        </div>

        <div id={'contact'} className={`${styles.page} ${styles.projects}`}>
          <ul>
            <li><a href="mailto:hi@domthedev.com">hi@domthedev.com</a></li>
          </ul>
        </div>
      </main>
    </div>
  )
}
